export type CodegenColumnType = 'string' | 'number' | 'boolean' | 'datetime';

export interface CodegenColumn {
  name: string;
  type: CodegenColumnType;
  nullable: boolean;
}

export interface EmitTypescriptSdkInput {
  /** Internal sheetforge sheet id (UUID). */
  sheetId: string;
  /** The Google Sheet tab name — used only to pick a sensible TypeScript type name. */
  tabName: string;
  /** Header-inferred columns in declaration order. */
  columns: CodegenColumn[];
  /** Base URL where the sheetforge API is hosted. */
  apiBaseUrl: string;
}

/**
 * Emit a self-contained TypeScript SDK file for one sheet. Users commit this
 * file directly — no runtime dependency on a published sheetforge client.
 *
 * The emitted module exports:
 *   - a typed interface for the row shape
 *   - a `create<Type>Client(...)` factory that takes an API key and returns
 *     list() / create() methods
 */
export function emitTypeScriptSdk(input: EmitTypescriptSdkInput): string {
  const typeName = toPascalIdentifier(input.tabName) || 'Row';
  const fields = input.columns
    .map((c) => {
      const ts = tsTypeOf(c.type);
      const key = jsonKey(c.name);
      return `  ${key}${c.nullable ? '?' : ''}: ${ts};`;
    })
    .join('\n');

  const clientName = `${typeName}Client`;
  const factoryName = `create${typeName}Client`;
  const baseUrlLiteral = JSON.stringify(input.apiBaseUrl);
  const sheetIdLiteral = JSON.stringify(input.sheetId);

  return `// Auto-generated by @sheetforge/codegen — do not edit by hand.
// Sheet: ${input.sheetId} / tab: ${input.tabName}
// Regenerate when headers change:  sheetforge regen ${input.sheetId}

export interface ${typeName} {
${fields}
}

export interface SubmitResult {
  writeId: string;
  status: 'enqueued' | 'replayed';
  messageId?: string;
}

export interface ${clientName} {
  list(): Promise<${typeName}[]>;
  create(
    row: ${typeName},
    options?: { idempotencyKey?: string },
  ): Promise<SubmitResult>;
}

export function ${factoryName}(opts: {
  apiKey: string;
  baseUrl?: string;
  fetch?: typeof globalThis.fetch;
}): ${clientName} {
  const base = opts.baseUrl ?? ${baseUrlLiteral};
  const sheetId = ${sheetIdLiteral};
  const doFetch = opts.fetch ?? globalThis.fetch;
  const authHeader = { Authorization: \`Bearer \${opts.apiKey}\` };

  return {
    async list() {
      const res = await doFetch(\`\${base}/v1/sheets/\${sheetId}/rows\`, {
        headers: { ...authHeader },
      });
      if (!res.ok) {
        throw new Error(\`sheetforge list failed: \${res.status} \${res.statusText}\`);
      }
      const body = (await res.json()) as { rows: ${typeName}[] };
      return body.rows;
    },

    async create(row, options) {
      const headers: Record<string, string> = {
        ...authHeader,
        'Content-Type': 'application/json',
      };
      if (options?.idempotencyKey) {
        headers['Idempotency-Key'] = options.idempotencyKey;
      }
      const res = await doFetch(\`\${base}/v1/sheets/\${sheetId}/rows\`, {
        method: 'POST',
        headers,
        body: JSON.stringify(row),
      });
      if (!res.ok) {
        throw new Error(\`sheetforge create failed: \${res.status} \${res.statusText}\`);
      }
      return (await res.json()) as SubmitResult;
    },
  };
}
`;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function tsTypeOf(t: CodegenColumnType): string {
  switch (t) {
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'datetime':
      // ISO-8601 strings keep the shape serialisable. Callers cast to Date if they want.
      return 'string';
    default:
      return 'string';
  }
}

function toPascalIdentifier(s: string): string {
  const words = s
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .split(/\s+/)
    .filter(Boolean);
  return words
    .map((w) => {
      const first = w[0];
      return first ? first.toUpperCase() + w.slice(1).toLowerCase() : '';
    })
    .join('');
}

function jsonKey(name: string): string {
  // If the header is a safe JS identifier, emit it bare; otherwise quote it.
  if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)) return name;
  return JSON.stringify(name);
}
